services:
  - type: web
    name: fitness-backend
    runtime: node
    rootDir: backend_nestjs
    buildCommand: npm install && npx prisma generate && node --max-old-space-size=512 node_modules/.bin/nest build
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
